name: Deploy the Resume Parser Cloud Function

on:
  push:
    paths:
      - resumeparser/**

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: "reezanvisramportfolio-resumeparser"
          runtime: "python311"
          entry_point: "parse_resume"
          memory_mb: "128"
          region: "us-central1"
          source_dir: "./resumeparser"
          event_trigger_type: "google.storage.object.finalize"
          event_trigger_resource: "projects/reezan-visram-projects/buckets/reezanvisramportfolio-static-files"
          env_vars: GCP_PROJECT_ID=reezan-visram-projects,CLOUDSTORAGE_BUCKET_NAME=reezanvisramportfolio-static-files,CLOUDSTORAGE_FILENAME_TO_FETCH=resume.pdf,CLOUDSTORAGE_FILENAME_TO_DOWNLOAD_TO=./resume.pdf
