name: Build and Deploy server to Cloud Run

on:
  push:
    paths:
      - server/**
env:
  PROJECT_ID: reezan-visram-projects
  GAR_LOCATION: us-central1
  SERVICE: reezanvisramportfolio-server
  REPOSITORY: reezanvisramportfolio
  REGION: us-central1
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Build
        run: cd server && go build -v ./...

      - name: Test
        run: cd server && go test -v ./...

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build_and_test
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-actions@v1"
        with:
          username: _json_key
          password: "${{ secrets.GCP_CREDENTIALS }}"
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
